# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: ${ECR_BASE_IMAGE_URL}:circleci-ruby2.7.1-v20200930
        aws_auth:
          aws_access_key_id: ${AWS_ACCESS_KEY_ID}
          aws_secret_access_key: ${AWS_SECRET_ACCESS_KEY}
        environment:
          PG_HOST: localhost
          PG_USER: circleci
          RAILS_ENV: test
          RACK_ENV: test
          DATABASE_URL: postgres://circleci:@localhost:5432/base_portal_test

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/postgres:12.3
        environment:
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_USER: circleci
          POSTGRES_DB: base_portal_test
          POSTGRES_PASSWORD: ""
      - image: selenium/standalone-chrome-debug
        environment:
          SCREEN_HEIGHT: 1600
          VNC_PASSWORD: secret

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      # collect reports
      - store_test_results:
          path: /tmp/test-results

      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
